# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SvetovaKuchyne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
            ],
        ),
    ]
