# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0005_uzivatel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
