# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0006_auto_20171203_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
            ],
        ),
    ]
