# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepty', '0007_ingredience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uzivatel',
        ),
        migrations.AddField(
            model_name='komentar',
            name='autor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kuchar',
            name='kuchar',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
