# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0008_auto_20171207_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='komentovany_recept',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recepty.Recepty'),
        ),
    ]
