# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0009_komentar_komentovany_recept'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='nadpis',
            field=models.CharField(default='nadpis', max_length=100),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
