# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0011_auto_20171207_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='hodnoceni',
            field=models.IntegerField(default=0),
        ),
    ]
