# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 06:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0013_auto_20171207_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='recept',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='recept',
            name='hodnoceni',
            field=models.FloatField(default=2.5),
        ),
    ]
