# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 07:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0014_auto_20171208_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 8, 0, 19, 748989)),
        ),
        migrations.AlterField(
            model_name='recept',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 8, 0, 19, 747989)),
        ),
    ]
