# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 07:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0015_auto_20171208_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 8, 11, 27, 57877)),
        ),
        migrations.AlterField(
            model_name='recept',
            name='hodnoceni',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=2),
        ),
        migrations.AlterField(
            model_name='recept',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 8, 11, 27, 56876)),
        ),
    ]
