# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 07:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0020_auto_20171208_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuchar',
            name='hodnoceni',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 8, 29, 8, 234813)),
        ),
        migrations.AlterField(
            model_name='recept',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 8, 29, 8, 233813)),
        ),
    ]
