# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 08:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0023_auto_20171208_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuchar',
            name='jmeno',
            field=models.CharField(default='jmeno', max_length=200),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 9, 1, 55, 272377)),
        ),
        migrations.AlterField(
            model_name='recept',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 9, 1, 55, 271376)),
        ),
    ]
