# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 08:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0025_auto_20171208_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zprava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nadpis', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='komentar',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 9, 51, 19, 360941)),
        ),
        migrations.AlterField(
            model_name='recept',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 9, 51, 19, 359940)),
        ),
    ]
