# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0027_auto_20171208_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kuchar',
            name='user',
        ),
        migrations.AlterField(
            model_name='komentar',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 10, 1, 35, 250835)),
        ),
        migrations.AlterField(
            model_name='recept',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 10, 1, 35, 249835)),
        ),
        migrations.DeleteModel(
            name='Kuchar',
        ),
    ]
