# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0030_auto_20171208_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 10, 50, 35, 808064)),
        ),
        migrations.AlterField(
            model_name='recept',
            name='postup',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='recept',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 10, 50, 35, 807564)),
        ),
    ]
