# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 10:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0031_auto_20171208_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='zprava',
            name='odesilatel',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 11, 15, 33, 831296)),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='text',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='recept',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 11, 15, 33, 829795)),
        ),
        migrations.AlterField(
            model_name='zprava',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
