# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0032_auto_20171208_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='svetova_kuchyne',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recepty.SvetovaKuchyne'),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 12, 18, 44, 964223)),
        ),
        migrations.AlterField(
            model_name='recept',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 12, 18, 44, 963223)),
        ),
    ]
