# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 16:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepty', '0034_auto_20171208_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clanek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nadpis', models.CharField(max_length=100)),
                ('text', models.TextField(default='', max_length=5000)),
                ('publikovano', models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 9, 17, 6, 25, 928513))),
                ('autor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fotogalerie',
            name='fotka',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 9, 17, 6, 25, 927513)),
        ),
        migrations.AlterField(
            model_name='recept',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 9, 17, 6, 25, 926512)),
        ),
    ]
