# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 16:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0035_auto_20171209_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='ingredience',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='clanek',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 9, 17, 27, 35, 721620)),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 9, 17, 27, 35, 720619)),
        ),
        migrations.AlterField(
            model_name='recept',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 9, 17, 27, 35, 719619)),
        ),
    ]
