# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0036_auto_20171209_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Ingredience',
        ),
        migrations.AlterField(
            model_name='clanek',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 9, 17, 32, 59, 221683)),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 9, 17, 32, 59, 220683)),
        ),
        migrations.AlterField(
            model_name='recept',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 9, 17, 32, 59, 219682)),
        ),
    ]
