# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0037_auto_20171209_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='chod',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recepty.Chod'),
        ),
        migrations.AlterField(
            model_name='clanek',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 9, 17, 33, 48, 937538)),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 9, 17, 33, 48, 936537)),
        ),
        migrations.AlterField(
            model_name='recept',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 9, 17, 33, 48, 935537)),
        ),
    ]
