# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 16:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0038_auto_20171209_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotogalerie',
            name='fotka',
        ),
        migrations.AlterField(
            model_name='clanek',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 9, 17, 45, 39, 435465)),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 9, 17, 45, 39, 434464)),
        ),
        migrations.AlterField(
            model_name='recept',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 9, 17, 45, 39, 433462)),
        ),
    ]
