# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 11:42
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0040_auto_20171209_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanek',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 13, 12, 42, 11, 808221)),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 13, 12, 42, 11, 808221)),
        ),
        migrations.AlterField(
            model_name='recept',
            name='hodnoceni',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recept',
            name='publikovano',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 13, 12, 42, 11, 808221)),
        ),
    ]
